Models/ReporteTransaccionesDetalladas.cs
namespace WebManejoPresupuestos.Models
{
    public class ReporteTransaccionesDetalladas
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public IEnumerable<TransaccionesPorFecha> TransaccionesAgrupadas { get; set; }
        public decimal BalanceDepositos => TransaccionesAgrupadas.Sum(x => x.BalanceDepositos);
        public decimal BalanceRetiros => TransaccionesAgrupadas.Sum(x => x.BalanceRetiros);
        public decimal Total => BalanceDepositos - BalanceRetiros;

        // clase interna para manejar las transacciones por fecha.
        // solo se utilizara en este modelo.
        public class TransaccionesPorFecha
        {
            public DateTime FechaTransaccion { get; set; }
            public IEnumerable<Transaccion> Transacciones { get; set; }
            public decimal BalanceDepositos => this.Transacciones
                                                        .Where(x => x.TipoOperacionId == TipoOperacion.Ingreso)
                                                        .Sum(m => m.Monto);
            public decimal BalanceRetiros => this.Transacciones
                                                     .Where(x => x.TipoOperacionId == TipoOperacion.Gasto)
                                                     .Sum(m => m.Monto);
        }
    }
}

Models/ResumenMontosViewModel.cs
namespace WebManejoPresupuestos.Models
{
    public class ResumenMontosViewModel
    {
        public decimal Ingresos { get; set; }
        public decimal Gastos { get; set; }
        public decimal Total { get; set; }
    }
}

Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using WebManejoPresupuestos.Models;
using WebManejoPresupuestos.Servicios;

namespace WebManejoPresupuestos.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly IRepositorioCategorias repositorioCategorias;
        private readonly IServicioUsuarios repositorioUsuarios;

        public CategoriasController(IRepositorioCategorias repositorioCategorias,
                                    IServicioUsuarios repositorioUsuarios)
        {
            this.repositorioCategorias = repositorioCategorias;
            this.repositorioUsuarios = repositorioUsuarios;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = repositorioUsuarios.ObtenerUsuarioId();
            var categorias = await repositorioCategorias.Obtener(usuarioId);

            return View(categorias);

        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Categoria categoria)
        {
            if (!ModelState.IsValid)
            {
                return View(categoria);
            }

            var usuarioId = repositorioUsuarios.ObtenerUsuarioId();
            categoria.UsuarioId = usuarioId;
            await repositorioCategorias.Crear(categoria);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = repositorioUsuarios.ObtenerUsuarioId();
            var categoria = await repositorioCategorias.ObtenerPorId(id, usuarioId);

            if (categoria is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Categoria categoriaEditar)
        {
            if (!ModelState.IsValid)
            {
                return View(categoriaEditar);
            }

            var usuarioId = repositorioUsuarios.ObtenerUsuarioId();
            var categoria = await repositorioCategorias.ObtenerPorId(categoriaEditar.Id, usuarioId);

            if (categoria is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            categoriaEditar.UsuarioId = usuarioId;
            await repositorioCategorias.Actualizar(categoriaEditar);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = repositorioUsuarios.ObtenerUsuarioId();
            var categoria = await repositorioCategorias.ObtenerPorId(id, usuarioId);

            if (categoria is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarCategoria(int id)
        {
            var usuarioId = repositorioUsuarios.ObtenerUsuarioId();
            var categoria = await repositorioCategorias.ObtenerPorId(id, usuarioId);

            if (categoria is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCategorias.Borrar(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/TiposCuentasController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using WebManejoPresupuestos.Models;
using WebManejoPresupuestos.Servicios;

namespace WebManejoPresupuestos.Controllers
{
    public class TiposCuentasController : Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuarios repositorioServicioUsuarios;

        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuarios repositorioServicioUsuarios) 
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.repositorioServicioUsuarios = repositorioServicioUsuarios;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);

            return View(tiposCuentas);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TiposCuentas cuenta)
        {
            // los metodos que utilicen metodos 'await async' tambien deben ser 'await async'
            // usamos 'await async' de abajo hacia arriba.

            if(!ModelState.IsValid) // si un campo no es valido regresamos.
            {
                return View(cuenta);
            }

            cuenta.UsuarioId = 
                repositorioServicioUsuarios.ObtenerUsuarioId();

            bool cuentaExiste = await repositorioTiposCuentas
                                      .Existe(cuenta.Nombre, cuenta.UsuarioId);

            if (cuentaExiste) 
            {
                ModelState.AddModelError(nameof(cuenta.Nombre), 
                $"La cuenta {cuenta.Nombre} ya existe.");
                return View(cuenta);
            }
            
            // si el modelo es valido y no existe la cuenta insertamos asincronamente
            await repositorioTiposCuentas.Crear(cuenta);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Editar(int id) 
        {
            var usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }


        [HttpPost]
        public async Task<ActionResult> Editar(TiposCuentas tipoCuenta)
        {
            var usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            var tipoCuentaExiste = await repositorioTiposCuentas
                                         .ObtenerPorId(tipoCuenta.Id, usuarioId);
            
            if (tipoCuentaExiste is null) 
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTiposCuentas.Actualizar(tipoCuenta);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public async Task<IActionResult> Borrar(int Id)
        {
            var usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(Id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }


        [HttpPost]
        public async Task<IActionResult> BorrarTipoCuenta(int Id) 
        {
            var usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(Id, usuarioId);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTiposCuentas.Borrar(Id);
            return RedirectToAction("Index");
        }


        [HttpGet] // con este metodo validamos sin pulsar enviar.
        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre) 
        {
            var usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            
            var yaExiste = await repositorioTiposCuentas.Existe(nombre, usuarioId);

            if (yaExiste) 
            {
                return Json($"La cuenta {nombre} ya existe.");
            }

            return Json(true);
        }


        [HttpPost]
        public async Task<IActionResult> Ordenar([FromBody] int[] ids) 
        {
            int usuarioId = repositorioServicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            var idsTiposCuentas = tiposCuentas.Select(x => x.Id);

            var idsTiposCuentasNoSonDelUsuario = ids.Except(idsTiposCuentas).ToList();

            if (idsTiposCuentasNoSonDelUsuario.Count > 0) 
            {
                return Forbid();
            }

            var tiposCuentasOrdenados = ids.Select((value, index) => 
                    new TiposCuentas() {Id = value, Orden = index + 1}
            ).AsEnumerable();

            await repositorioTiposCuentas.Ordenar(tiposCuentasOrdenados);

            return Ok();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Manejo Presupuestos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebManejoPresupuestos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="WebManejoPresupuestos.styles.css" asp-append-version="true" />
    <!--Full calendar-->
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css" />

    <!-- Iconos de bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Transacciones" asp-action="Index">Manejo Presupuestos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Transacciones" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Manejo Presupuestos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- primero deben renderizarse estos scripts, al ultimo los reder section -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-UI/jquery-ui.min.js"></script> <!-- mejora de experiencia de usuario gui -->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false) <!-- Aqui se renderizan los scripts -->
</body>
</html>

Views/Shared/_NavegarPorMeses.cshtml
@model DateTime

<h4>
    <!--control para navegar a la fecha anterior-->
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-año="@ViewBag.yearAnterior"
       class="btn btn-secondary"> <i class="bi-chevron-left"> </i> </a>

    @Model.ToString("MMM") - @Model.Year

    <!--control para navegar a la fecha posterior-->
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-año="@ViewBag.yearPosterior"
       class="btn btn-secondary"> <i class="bi-chevron-right"></i> </a>
</h4>

Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model ReporteTransaccionesDetalladas

@{
    var resumenMontos = new ResumenMontosViewModel()
    {
        Ingresos = Model.BalanceDepositos,
        Gastos = Model.BalanceRetiros,
        Total = Model.Total
    };
}

<!-- VISTA PARCIAL DE MOVIMIENTO DEL REPORTE EN ./SHARED/ 📁 PARA SER REUTILIZALE -->

<partial name="_NavegarPorMeses" model="@Model.FechaInicio"/>

<br />
<!--vista parcial del resumen de la cuenta-->
<partial name="_ResumenMontos" model="@resumenMontos" />

<!--informacion de las transacciones-->
@if (Model.TransaccionesAgrupadas.Count() == 0)
{
    <!--Mensaje No encontrado-->
    <div style="padding: 20px 0;align-items: center; color: royalblue; font-family: Calibri;">

        <h1 style="font-size: 60px">:(</h1>
        <h3>No hay datos para mostrar</h3>
        <p>No se han realizado operaciones en este mes, ¿Cree que olvido algo? agrege una nueva transaccion.</p>

    </div>
}
else
{
    <table class="table rounded rounded-3 overflow-hidden">

        <tbody>
            @foreach (var transaccionAgrupada in Model.TransaccionesAgrupadas)
            {
                <tr style="background-color: lightcyan; font-size: 26px;">

                    <td colspan="3">
                        @transaccionAgrupada.FechaTransaccion.Day
                        <span class="badge bg-info">
                            @transaccionAgrupada.FechaTransaccion.ToString("ddd")
                        </span>
                    </td>

                    <td class="activo">@transaccionAgrupada.BalanceDepositos.ToString("N")</td>

                    <td class="pasivo">@transaccionAgrupada.BalanceRetiros.ToString("N")</td>

                </tr>

                <!--Transacciones de la transaccion agrupada por fecha-->
                @foreach (var transaccion in transaccionAgrupada.Transacciones)
                {
                    <tr style="vertical-align: middle">
                        <td>
                            <a asp-controller="Transacciones" asp-action="Editar" asp-route-id="@transaccion.Id" asp-route-urlRetorno="@ViewBag.urlRetorno">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>

                        <td>@transaccion.Categoria</td>

                        <td>@transaccion.Cuenta</td>

                        <td class="activo">
                            @(transaccion.TipoOperacionId == TipoOperacion.Ingreso ? transaccion.Monto.ToString("N") : "N/A")
                        </td>

                        <td class="pasivo">
                            @(transaccion.TipoOperacionId == TipoOperacion.Gasto ? transaccion.Monto.ToString("N") : "N/A")
                        </td>
                    </tr>
                }
            }
        </tbody>

    </table>
}

Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosViewModel

<div class="contenedor-totales mb-3">

    <div>
        <div><strong>DEPOSITOS</strong></div>
        <div class="activo">@Model.Ingresos.ToString("N")</div>
    </div>

    <div>
        <div><strong>RETIROS</strong></div>
        <div class="pasivo">@Model.Gastos.ToString("N")</div>
    </div>

    <div>
        <div><strong>TOTAL</strong></div>
        <div>@Model.Total.ToString("N")</div>
    </div>

</div>


@* <div class="card">

    <div class="card-body">
        <div class="contenedor-totales mb-3">

            <div>
                <div><strong>DEPOSITOS</strong></div>
                <div class="activo">@Model.Ingresos.ToString("N")</div>
            </div>

            <div>
                <div><strong>RETIROS</strong></div>
                <div class="pasivo">@Model.Gastos.ToString("N")</div>
            </div>

            <div>
                <div><strong>TOTAL</strong></div>
                <div>@Model.Total.ToString("N")</div>
            </div>

        </div>
    </div>

</div> *@